type:       map
mapping:
  "ldap_connection":
    type:      any
    required:  yes

  "ldap_users":
    type: map
    required: yes
    mapping:
      "base":
        type: str
        required:  yes
      "filter":
        type: str
        required:  yes
      "name_attribute":
        type: str
        required:  yes
      "lowercase_name":
        type: bool
        required:  no
      "bothcase_name":
        type: bool
        required:  no
      "uppercase_name":
        type: bool
        required: no

  "ldap_groups":
    type: map
    required: yes
    mapping:
      "base":
        type: str
        required:  yes
      "filter":
        type: str
        required:  yes
      "name_attribute":
        type: str
        required:  yes
      "lowercase_name":
        type: bool
        required:  no
      "bothcase_name":
        type: bool
        required:  no
      "uppercase_name":
        type: bool
        required: no
      "member_attribute":
        type: str
        required:  yes
      "ald_domain":
        type: bool
        required: no

  "pg_connection":
    type:      any
    required:  yes

  "pg_users":
    type: map
    required: yes
    mapping:
      "filter":
        type: str
        required:  yes
      "create_options":
        type: str

  "pg_groups":
    type: map
    required: yes
    mapping:
      "filter":
        type: str
        required:  yes
      "create_options":
        type: str
      "grant_options":
        type: str
